export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

//app
export const ADD_APP_REQUEST = "ADD_APP_REQUEST";
export const ADD_APP_SUCCESS = "ADD_APP_SUCCESS";
export const ADD_APP_FAIL = "ADD_APP_FAIL";

export const LIST_APPS_USER_REQUEST = "LIST_APPS_USER_REQUEST";
export const LIST_APPS_USER_SUCCESS = "LIST_APPS_USER_SUCCESS";
export const LIST_APPS_USER_FAIL = "LIST_APPS_USER_FAIL";

export const UPDATE_APP_REQUEST = "UPDATE_APP_REQUEST";
export const UPDATE_APP_SUCCESS = "UPDATE_APP_SUCCESS";
export const UPDATE_APP_FAIL = "UPDATE_APP_FAIL";

export const LIST_APPS_REQUEST = "LIST_APPS_REQUEST";
export const LIST_APPS_SUCCESS = "LIST_APPS_SUCCESS";
export const LIST_APPS_FAIL = "LIST_APPS_FAIL";

export const DELETE_APP_REQUEST = "DELETE_APP_REQUEST";
export const DELETE_APP_SUCCESS = "DELETE_APP_SUCCESS";
export const DELETE_APP_FAIL = "DELETE_APP_FAIL";

export const ADD_GOAL_REQUEST = "ADD_GOAL_REQUEST";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FAIL = "ADD_GOAL_FAIL";
